export const strings = {
  'en': {
    list: 'List',
    add: 'Add',
    edit: 'Edit',
    delete: 'Delete',
    clear: 'Clear',
    language: 'Language',
    exit: 'Exit',
    chooseOption: 'Choose an option:',
    chooseLanguage: 'Choose a language:',
    answer: `      message += '\\n  Answer: ';`,
    validIndex: `    this.render('Please enter a valid index');`,
    yesNo: `    this.opt.default = rawDefault ? 'y/n' : 'y/N';`,
    currentLanguage: 'Current language',
    exiting: 'Exiting the application...',
    taskEditNumber: 'Enter the number of the task to be edited:',
    invalidNumber: 'Invalid Number',
    editedTask: 'Enter the edited task:',
    processing: 'Processing...',
    editSuccess: 'Task edited successfully',
    taskDeleteNumber: 'Enter the number of the task to be deleted:',
    confirmDelete: 'Are you sure you want to delete the task',
    cancelDelete: 'Canceled by user',
    deleteSuccess: 'Task deleted successfully',
    addTask: 'Enter the task:',
    noTask: 'You have not entered a task',
    addSuccess: 'Task added successfully',
    langIsNotDefined: 'Language is not defined'
  },
  'pt-br': {
    list: 'Listar',
    add: 'Adicionar',
    edit: 'Editar',
    delete: 'Deletar',
    clear: 'Limpar',
    language: 'Linguagem',
    exit: 'Sair',
    chooseOption: 'Escolha uma opção:',
    chooseLanguage: 'Escolha uma linguagem:',
    answer: `      message += '\\n  Resposta: ';`,
    validIndex: `    this.render('Insira um índice válido');`,
    yesNo: `    this.opt.default = rawDefault ? 's/n' : 'S/N';`,
    currentLanguage: 'Linguagem atual',
    exiting: 'Saindo da aplicação...',
    taskEditNumber: 'Digite o número da tarefa a ser editada:',
    invalidNumber: 'Número inválido',
    editedTask: 'Digite a tarefa editada:',
    processing: 'Processando...',
    editSuccess: 'Tarefa editada com sucesso',
    taskDeleteNumber: 'Digite o número da tarefa a ser deletada:',
    confirmDelete: 'Tem certeza que deseja excluir a tarefa',
    cancelDelete: 'Cancelado pelo usuário',
    deleteSuccess: 'Tarefa deletada com sucesso',
    addTask: 'Digite a tarefa:',
    noTask: 'Você não digitou uma tarefa',
    addSuccess: 'Tarefa adicionada com sucesso',
    langIsNotDefined: 'Linguagem não definida'
  },
  'es': {
    list: 'Lista',
    add: 'Agregar',
    edit: 'Editar',
    delete: 'Borrar',
    clear: 'Limpiar',
    language: 'Idioma',
    exit: 'Salir',
    chooseOption: 'Elige una opción:',
    chooseLanguage: 'Elige un idioma:',
    answer: `      message += '\\n  Respuesta: ';`,
    validIndex: `    this.render('Por favor ingrese un índice válido');`,
    yesNo: `    this.opt.default = rawDefault ? 's/n' : 'S/N';`,
    currentLanguage: 'Idioma actual',
    exiting: 'Saliendo de la aplicación...',
    taskEditNumber: 'Ingrese el número de la tarea a editar:',
    invalidNumber: 'Número invalido',
    editedTask: 'Ingrese la tarea editada:',
    processing: 'Procesando...',
    editSuccess: 'Tarea editada exitosamente',
    taskDeleteNumber: 'Ingrese el número de la tarea a eliminar:',
    confirmDelete: '¿Estás seguro de que deseas eliminar la tarea?',
    cancelDelete: 'Cancelado por el usuario',
    deleteSuccess: 'Tarea eliminada exitosamente',
    addTask: 'Ingrese la tarea:',
    noTask: 'No has ingresado una tarea',
    addSuccess: 'Tarea agregada exitosamente',
    langIsNotDefined: 'El idioma no está definido'
  },
};
